### ISSUE TITLE
Max retries reached

### ISSUE THREAD

**Issue by zyb8543d** [modelscope/ms-agent#316]
codes：
```
@register_tool('RenewInstance')
class AliyunRenewInstanceTool(BaseTool):
    description = '续费一台包年包月ECS实例'
    name = 'RenewInstance'
    parameters: list = [{
        'name': 'instance_id',
        'description': 'ECS实例ID',
        'required': True,
        'type': 'string'
    }, {
        'name': 'period',
        'description': '续费时长以月为单位',
        'required': True,
        'type': 'string'
    }]

    def call(self, params: str, **kwargs):
        params = self._verify_args(params)
        instance_id = params['instance_id']
        period = params['period']
        return str({'result': f'已完成ECS实例ID为{instance_id}的续费，续费时长{period}月'})


role_template = '你扮演一名ECS实例管理员，你需要根据用户的要求来满足他们'
llm_config = {
    'model': '/data/disk2/ybZhang/Chinese-LLM-Chat/models/qwen-7b-chat',
    'model_server': 'modelscope',
    }
function_list = ['RenewInstance']

bot = RolePlay(function_list=function_list,llm=llm_config, instruction=role_template)
response = bot.run("请帮我续费一台ECS实例，实例id是：i-rj90a7e840y5cde，续费时长10个月", remote=False, print_info=True)
text = ''
for chunk in response:
    text += chunk
print(text)

```
Error:
```
2024-02-29 11:30:34.317 - modelscope-agent - WARNING -  | message: Attempt to run chat_with_functions 1 failed:
2024-02-29 11:30:34.819 - modelscope-agent - WARNING -  | message: Attempt to run chat_with_functions 2 failed:
2024-02-29 11:30:35.320 - modelscope-agent - WARNING -  | message: Attempt to run chat_with_functions 3 failed:
2024-02-29 11:30:35.825 - modelscope-agent - ERROR -  | message: Traceback (most recent call last):
  File "/data/disk2/ybZhang/modelscope-agent/modelscope_agent/llm/base.py", line 192, in support_function_calling
    response = self.chat_with_functions(
  File "/data/disk2/ybZhang/modelscope-agent/modelscope_agent/utils/retry.py", line 38, in wrapper
    raise Exception('Max retries reached. Failed to get result')
Exception: Max retries reached. Failed to get result

2024-02-29 11:30:35.826 - modelscope-agent - WARNING -  | message: Attempt to run chat 1 failed:
2024-02-29 11:30:36.327 - modelscope-agent - WARNING -  | message: Attempt to run chat 2 failed:
2024-02-29 11:30:36.8
```

**Comment by mushenL** [comment]
您好，新版本暂时没有适配modelscope的model_serve，所以按照直接使用本地模型路径的话会有报错，现阶段推荐使用demo中所用的远程模型调用，如果本地部署的话建议使用https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md文档所描述的部署方案进行部署，

**Comment by v-yunbin** [comment]
> 您好，新版本暂时没有适配modelscope的model_serve，所以按照直接使用本地模型路径的话会有报错，现阶段推荐使用demo中所用的远程模型调用，如果本地部署的话建议使用[https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md文档所描述的部署方案进行部署，](https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md%E6%96%87%E6%A1%A3%E6%89%80%E6%8F%8F%E8%BF%B0%E7%9A%84%E9%83%A8%E7%BD%B2%E6%96%B9%E6%A1%88%E8%BF%9B%E8%A1%8C%E9%83%A8%E7%BD%B2%EF%BC%8C)

@mushenL 你好，这个文档不存在：https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md

**Comment by mushenL** [comment]
![image](https://github.com/modelscope/modelscope-agent/assets/125954878/b7ae2a84-88a1-4114-95d6-02503477cab7)
您好，我这边看是文档是存在的，可以检查一下分支是否正确
https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md

**Comment by v-yunbin** [comment]
> ![image](https://private-user-images.githubusercontent.com/125954878/309230149-b7ae2a84-88a1-4114-95d6-02503477cab7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjgyNjcsIm5iZiI6MTcwOTYyNzk2NywicGF0aCI6Ii8xMjU5NTQ4NzgvMzA5MjMwMTQ5LWI3YWUyYTg0LTg4YTEtNDExNC05NWQ2LTAyNTAzNDc3Y2FiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwODM5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmI4MDU1Y2I2NTA5NTNmZjVkNGRkYzc0Mjg2Y2Q1MDU2NjhkZDgzYTY0OTAyYWQxMTNiMzg4NjE4NTc1YjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cT_kq31B8fKgHuh6-frOdhJvxAvlQRmJwIMCtjwstRg) 您好，我这边看是文档是存在的，可以检查一下分支是否正确 https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md

后续会支持加载本地模型吗?

**Comment by zzhangpurdue** [comment]
> > ![image](https://private-user-images.githubusercontent.com/125954878/309230149-b7ae2a84-88a1-4114-95d6-02503477cab7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjgyNjcsIm5iZiI6MTcwOTYyNzk2NywicGF0aCI6Ii8xMjU5NTQ4NzgvMzA5MjMwMTQ5LWI3YWUyYTg0LTg4YTEtNDExNC05NWQ2LTAyNTAzNDc3Y2FiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwODM5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmI4MDU1Y2I2NTA5NTNmZjVkNGRkYzc0Mjg2Y2Q1MDU2NjhkZDgzYTY0OTAyYWQxMTNiMzg4NjE4NTc1YjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cT_kq31B8fKgHuh6-frOdhJvxAvlQRmJwIMCtjwstRg) 您好，我这边看是文档是存在的，可以检查一下分支是否正确 https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md
> 
> 后续会支持加载本地模型吗?
本地模型可以通过vllm 的方式拉起, 参考：https://github.com/modelscope/modelscope-agent/blob/master/docs/local_deploy.md
