### ISSUE TITLE
无外网部署报错

### ISSUE THREAD

**Issue by zyb8543d** [modelscope/ms-agent#327]
```
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/utils.py", line 673, in gen_wrapper
    response = next(iterator)
  File "/root/work2/ybZhang/Chinese-LLM-Chat/agent/modelscope-agent/apps/agentfabric/app.py", line 731, in init_all
    builder_cfg, model_cfg, tool_cfg, available_tool_list, _, _ = parse_configuration(
  File "/root/work2/ybZhang/Chinese-LLM-Chat/agent/modelscope-agent/apps/agentfabric/config_utils.py", line 142, in parse_configuration
    model_cfg = Config.from_file(model_cfg_file)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/modelscope/utils/config.py", line 132, in from_file
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/modelscope/utils/config.py", line 117, in _file2dict
    cfg_dict = load(tmp_cfg_file.name)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/modelscope/fileio/io.py", line 48, in load
    obj = handler.load(f, **kwargs)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/modelscope/fileio/format/json.py", line 28, in load
    return jsonplus.loads(file.read())
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/modelscope/fileio/format/jsonplus.py", line 317, in loads
    return json.loads(*pa, **kw)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/simplejson/__init__.py", line 533, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting ',' delimiter or '}': line 112 column 5 (char 2704)
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f6158f8d360>
Traceback (most recent call last):
  File "/opt/conda/envs/msagent/lib/python3.10/tempfile.py", line 450, in __del__
    self.close()
  File "/opt/conda/envs/msagent/lib/python3.10/tempfile.py", line 446, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpt3yftff0/tmpkwxfo516.json'
^[[B^[[BTraceback (most recent call last):
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/gradio/utils.py", line 673, in gen_wrapper
    response = next(iterator)
  File "/root/work2/ybZhang/Chinese-LLM-Chat/agent/modelscope-agent/apps/agentfabric/app.py", line 731, in init_all
    builder_cfg, model_cfg, tool_cfg, available_tool_list, _, _ = parse_configuration(
  File "/root/work2/ybZhang/Chinese-LLM-Chat/agent/modelscope-agent/apps/agentfabric/config_utils.py", line 142, in parse_configuration
    model_cfg = Config.from_file(model_cfg_file)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/modelscope/utils/config.py", line 132, in from_file
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/modelscope/utils/config.py", line 117, in _file2dict
    cfg_dict = load(tmp_cfg_file.name)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/modelscope/fileio/io.py", line 48, in load
    obj = handler.load(f, **kwargs)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/modelscope/fileio/format/json.py", line 28, in load
    return jsonplus.loads(file.read())
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/modelscope/fileio/format/jsonplus.py", line 317, in loads
    return json.loads(*pa, **kw)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/simplejson/__init__.py", line 533, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/opt/conda/envs/msagent/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting ',' delimiter or '}': line 112 column 5 (char 2704)
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f6158f8d360>
Traceback (most recent call last):
  File "/opt/conda/envs/msagent/lib/python3.10/tempfile.py", line 450, in __del__
    self.close()
  File "/opt/conda/envs/msagent/lib/python3.10/tempfile.py", line 446, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp9v3jv6oa/tmpicdybq7v.json'
```

**Comment by mushenL** [comment]
您好，从您的报错上来看，应该是gradio版本问题以及环境问题，请问您使用的是哪个分支的代码，是否已经更新到最新版本？以及您是通过哪个文件进行的本地部署？

**Comment by v-yunbin** [comment]
> 您好，从您的报错上来看，应该是gradio版本问题以及环境问题，请问您使用的是哪个分支的代码，是否已经更新到最新版本？以及您是通过哪个文件进行的本地部署？

按照安装文档一步一步来的，也按照暗转文档切换了分支qwen_vllm（origin/feat/qwen_vllm），gradio版本应该是什么版本

**Comment by mushenL** [comment]
分支qwen_vllm的部分已经合并到主干，使用主干的代码就可以，关于gradio版本参考一下 apps/agentfabric/requirements.txt，您也可以使用文档中推荐的镜像环境进行部署

**Comment by zzhangpurdue** [comment]
> > 您好，从您的报错上来看，应该是gradio版本问题以及环境问题，请问您使用的是哪个分支的代码，是否已经更新到最新版本？以及您是通过哪个文件进行的本地部署？
> 
> 按照安装文档一步一步来的，也按照暗转文档切换了分支qwen_vllm（origin/feat/qwen_vllm），gradio版本应该是什么版本

你好，拉最新的master是否能够解决？

**Comment by v-yunbin** [comment]
> > > 您好，从您的报错上来看，应该是gradio版本问题以及环境问题，请问您使用的是哪个分支的代码，是否已经更新到最新版本？以及您是通过哪个文件进行的本地部署？
> > 
> > 
> > 按照安装文档一步一步来的，也按照暗转文档切换了分支qwen_vllm（origin/feat/qwen_vllm），gradio版本应该是什么版本
> 
> 你好，拉最新的master是否能够解决？

这个我还没试，试了给你反馈。
我手写了一个，效果蛮不错。

**Comment by zzhangpurdue** [comment]
> > > > 您好，从您的报错上来看，应该是gradio版本问题以及环境问题，请问您使用的是哪个分支的代码，是否已经更新到最新版本？以及您是通过哪个文件进行的本地部署？
> > > 
> > > 
> > > 按照安装文档一步一步来的，也按照暗转文档切换了分支qwen_vllm（origin/feat/qwen_vllm），gradio版本应该是什么版本
> > 
> > 
> > 你好，拉最新的master是否能够解决？
> 
> 这个我还没试，试了给你反馈。 我手写了一个，效果蛮不错。

效果不错的话，可以看看最新的master，如果没有的话，可以看看贡献回来。
